// Generated by scripts/sync-homepage-content.mjs; originals and delivery provenance in content/homepage.json.
import image0 from "../assets/homepage/shanghai-480.webp";
import image1 from "../assets/homepage/shanghai-960.webp";
import image2 from "../assets/homepage/shanghai-1440.webp";
import image3 from "../assets/homepage/paris-480.webp";
import image4 from "../assets/homepage/paris-960.webp";
import image5 from "../assets/homepage/tokyo-480.webp";
import image6 from "../assets/homepage/tokyo-960.webp";
import image7 from "../assets/homepage/sydney-480.webp";
import image8 from "../assets/homepage/sydney-960.webp";
import image9 from "../assets/homepage/marrakech-480.webp";
import image10 from "../assets/homepage/marrakech-960.webp";
import image11 from "../assets/homepage/newYork-480.webp";
import image12 from "../assets/homepage/newYork-960.webp";
export const homepageImages = {
    shanghai: {src: image2, srcSet: image0 + " 480w" + ", " + image1 + " 960w" + ", " + image2 + " 1440w"},
    paris: {src: image4, srcSet: image3 + " 480w" + ", " + image4 + " 960w"},
    tokyo: {src: image6, srcSet: image5 + " 480w" + ", " + image6 + " 960w"},
    sydney: {src: image8, srcSet: image7 + " 480w" + ", " + image8 + " 960w"},
    marrakech: {src: image10, srcSet: image9 + " 480w" + ", " + image10 + " 960w"},
    newYork: {src: image12, srcSet: image11 + " 480w" + ", " + image12 + " 960w"},
};
