// Generated by npm run assets:optimize. Do not edit; source/derivative provenance is in optimized/manifest.json.
import image0 from "../assets/optimized/logo-icon-224.png";
import image1 from "../assets/optimized/hero-bg-1920.webp";
import image2 from "../assets/optimized/southeast-480.webp";
import image3 from "../assets/optimized/southeast-960.webp";
import image4 from "../assets/optimized/eastasia-480.webp";
import image5 from "../assets/optimized/eastasia-960.webp";
import image6 from "../assets/optimized/europe-480.webp";
import image7 from "../assets/optimized/europe-960.webp";
import image8 from "../assets/optimized/americas-480.webp";
import image9 from "../assets/optimized/americas-960.webp";
import image10 from "../assets/optimized/anz-480.webp";
import image11 from "../assets/optimized/anz-960.webp";
import image12 from "../assets/optimized/northAfrica-480.webp";
import image13 from "../assets/optimized/northAfrica-960.webp";
import image14 from "../assets/optimized/southeast-asia-banner-1600.webp";
import image15 from "../assets/optimized/east-asia-banner-1600.webp";
import image16 from "../assets/optimized/europe-banner-1600.webp";
import image17 from "../assets/optimized/americas-banner-1600.webp";
import image18 from "../assets/optimized/oceania-banner-1600.webp";
import image19 from "../assets/optimized/africa-banner-1600.webp";
import image20 from "../assets/optimized/france-480.webp";
import image21 from "../assets/optimized/france-960.webp";
import image22 from "../assets/optimized/germany-480.webp";
import image23 from "../assets/optimized/germany-960.webp";
import image24 from "../assets/optimized/greece-480.webp";
import image25 from "../assets/optimized/greece-960.webp";
import image26 from "../assets/optimized/italy-480.webp";
import image27 from "../assets/optimized/italy-960.webp";
import image28 from "../assets/optimized/netherlands-480.webp";
import image29 from "../assets/optimized/netherlands-960.webp";
import image30 from "../assets/optimized/portugal-480.webp";
import image31 from "../assets/optimized/portugal-960.webp";
import image32 from "../assets/optimized/spain-480.webp";
import image33 from "../assets/optimized/spain-960.webp";
import image34 from "../assets/optimized/switzerland-480.webp";
import image35 from "../assets/optimized/switzerland-960.webp";
import image36 from "../assets/optimized/united-kingdom-480.webp";
import image37 from "../assets/optimized/united-kingdom-960.webp";

export const optimizedImages = {
    "logo-icon": {src: image0, srcSet: image0 + " 224w", width: 224, height: 224},
    "hero-bg": {src: image1, srcSet: image1 + " 1920w", width: 1920, height: 1080},
    "southeast": {src: image3, srcSet: image2 + " 480w" + ", " + image3 + " 960w", width: 960, height: 640},
    "eastasia": {src: image5, srcSet: image4 + " 480w" + ", " + image5 + " 960w", width: 960, height: 1440},
    "europe": {src: image7, srcSet: image6 + " 480w" + ", " + image7 + " 960w", width: 960, height: 641},
    "americas": {src: image9, srcSet: image8 + " 480w" + ", " + image9 + " 960w", width: 960, height: 540},
    "anz": {src: image11, srcSet: image10 + " 480w" + ", " + image11 + " 960w", width: 960, height: 452},
    "northafrica": {src: image13, srcSet: image12 + " 480w" + ", " + image13 + " 960w", width: 960, height: 640},
    "southeast-asia-banner": {src: image14, srcSet: image14 + " 1600w", width: 1600, height: 1067},
    "east-asia-banner": {src: image15, srcSet: image15 + " 1600w", width: 1600, height: 1066},
    "europe-banner": {src: image16, srcSet: image16 + " 1600w", width: 1600, height: 1067},
    "americas-banner": {src: image17, srcSet: image17 + " 1600w", width: 1600, height: 755},
    "oceania-banner": {src: image18, srcSet: image18 + " 1600w", width: 1600, height: 900},
    "africa-banner": {src: image19, srcSet: image19 + " 1600w", width: 1600, height: 1066},
    "france": {src: image21, srcSet: image20 + " 480w" + ", " + image21 + " 960w", width: 960, height: 544},
    "germany": {src: image23, srcSet: image22 + " 480w" + ", " + image23 + " 960w", width: 960, height: 640},
    "greece": {src: image25, srcSet: image24 + " 480w" + ", " + image25 + " 960w", width: 960, height: 640},
    "italy": {src: image27, srcSet: image26 + " 480w" + ", " + image27 + " 960w", width: 960, height: 643},
    "netherlands": {src: image29, srcSet: image28 + " 480w" + ", " + image29 + " 960w", width: 960, height: 640},
    "portugal": {src: image31, srcSet: image30 + " 480w" + ", " + image31 + " 960w", width: 960, height: 641},
    "spain": {src: image33, srcSet: image32 + " 480w" + ", " + image33 + " 960w", width: 960, height: 639},
    "switzerland": {src: image35, srcSet: image34 + " 480w" + ", " + image35 + " 960w", width: 960, height: 640},
    "united kingdom": {src: image37, srcSet: image36 + " 480w" + ", " + image37 + " 960w", width: 960, height: 639},
};
