import sharp from "sharp";
import {mkdir, readFile, writeFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {fileURLToPath} from "node:url";
import {resolve} from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));
const output = resolve(root, "src/assets/optimized");
// Measured high-impact surfaces only. Originals remain the editable source of truth.
const plan = [
    {source: "logo-icon.png", widths: [224], format: "png"},
    {source: "hero-bg.jpg", widths: [1920]},
    ...["southeast", "eastasia", "europe", "americas", "anz", "northAfrica"].map(name => ({source: `${name}.jpg`, widths: [480, 960]})),
    ...["southeast-asia", "east-asia", "europe", "americas", "oceania", "africa"].map(name => ({source: `${name}-banner.jpg`, widths: [1600]})),
    ...["france", "germany", "greece", "italy", "netherlands", "portugal", "spain", "switzerland", "united kingdom"].map(name => ({source: `${name}.jpg`, widths: [480, 960]})),
];
const manifest = {};
await mkdir(output, {recursive: true});
for (const {source, widths, format = "webp"} of plan) {
    const original = await readFile(resolve(root, "src/assets", source));
    const metadata = await sharp(original).metadata();
    const name = source.replace(/\.[^.]+$/, "");
    const variants = [];
    for (const width of widths) {
        const file = `${name.replace(/\s+/g, "-")}-${width}.${format}`;
        const pipeline = sharp(original).rotate().resize({width, withoutEnlargement: true});
        const {data, info} = await (format === "png" ? pipeline.png({compressionLevel: 9}) : pipeline.webp({quality: 82, effort: 6})).toBuffer({resolveWithObject: true});
        await writeFile(resolve(output, file), data);
        variants.push({file, width: info.width, height: info.height, bytes: data.length});
    }
    manifest[name.toLowerCase()] = {source, sourceBytes: original.length,
        sourceSha256: createHash("sha256").update(original).digest("hex"),
        width: metadata.width, height: metadata.height, variants};
}
await writeFile(resolve(output, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
const imports = [], entries = [];
for (const [name, item] of Object.entries(manifest)) {
    const variables = item.variants.map(variant => {
        const variable = `image${imports.length}`;
        imports.push(`import ${variable} from "../assets/optimized/${variant.file}";`);
        return variable;
    });
    const largest = item.variants.at(-1);
    entries.push(`    ${JSON.stringify(name)}: {src: ${variables.at(-1)}, srcSet: ${item.variants.map((variant, index) => `${variables[index]} + " ${variant.width}w"`).join(' + ", " + ')}, width: ${largest.width}, height: ${largest.height}},`);
}
await writeFile(resolve(root, "src/utils/optimizedImages.js"),
    "// Generated by npm run assets:optimize. Do not edit; source/derivative provenance is in optimized/manifest.json.\n" + imports.join("\n") + "\n\nexport const optimizedImages = {\n" + entries.join("\n") + "\n};\n");
const exclusions = plan.filter(item => item.source.endsWith(".jpg")).map(item => `    "!../assets/${item.source}",`);
await writeFile(resolve(root, "src/utils/rootImages.js"),
    '// Generated by npm run assets:optimize. Optimized originals must not be emitted through this fallback glob.\nexport const rootImages = import.meta.glob([\n    "../assets/*.jpg",\n' + exclusions.join("\n") + '\n], {eager: true, import: "default"});\n');
console.log(`Generated ${plan.length} measured source representations (${imports.length} derivatives).`);
